# Site settings
baseURL = "https://comercio-latam.netlify.app/"
languageCode = "en-us"
title = "Comercio en América Latina"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Rebecca Hoffmann"
  description = "Comercio Exterior en América Latina"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Comercio América Latina"
    subtitle = "By Rebecca Hoffmann"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "https://comercio-latam.netlify.app/"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Comercio Exterior en América Latina"
    subtitle = "PROYECTO FINAL UTILIZANDO OPEN TRADE STATISTICS & BLOGDOWN"
    buttonText = "¿EMPEZAMOS?"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Introducción"
      subtitle = "Objetivos y instalando BlogDown"
      image = "pic1.jpg"
      url = "post/intro/"

    [[params.tiles.showcase]]
      title = "Comercio Exterior"
      subtitle = "La evolución histórica del comercio exterior en América Latina"
      image = "pic2.jpg"
      url = "post/comercio-latam/"

    [[params.tiles.showcase]]
      title = "Importación"
      subtitle = "Analisis de las importaciones en América Latina en 2018"
      image = "pic3.jpg"
      url = "post/importacion/"

    [[params.tiles.showcase]]
      title = "Exportación"
      subtitle = "Analisis de los productos exportados en América Latina en 2018"
      image = "pic4.jpg"
      url = "post/export/"

    [[params.tiles.showcase]]
      title = "Comercio Exterior en Argentina"
      subtitle = "Analisis del comercio exterior en Argentina"
      image = "pic5.jpg"
      url = "post/comercio-arg"

    [[params.tiles.showcase]]
      title = "Conclusión"
      subtitle = "Conclusión y consideraciones finales"
      image = "pic6.jpg"
      url = "post/conclusion"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "¿Dónde tiene América Latina su fuerza comercial?"
    subtitle = """ 
    Investigadores y políticos discuten como se puede generar un crecimiento más sostentable en América Latina. 
    El modelo económico de la ISI no generó el desarrollo deseado para la región. Tampoco los modelos neoliberales de los 1990s. 
    Investigadores recientes ha argumentado que es necesario un cambio profundo en los productos que se comercializan en América Latina,
    y que se necesita una base de trabajadores más calificados para empujar un cambio hacia producción en sectores de alta tecnología.
    No obstante, antes de poder dar soluciones, necesitamos entender la situación actual del comercio exterior en América Latina. 
    El objetivo de este proyecto es explorar algunas de los flujos de comercio exterior en América Latina. """
    buttonText = "Leer más"
    url = "post/intro/"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "hola@becci.com"

    [[params.contact.address]]
    title = "Address"
    city = "Buenos Aires"
    country = "Argentina"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Rebecca Hoffmann"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/becciabroad"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/becciabroad"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/becciabroad"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/rehoffmann/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
