---
title: Conclusión
author: Rebecca Hoffmann
date: '2020-12-07'
slug: conclusion
categories: []
tags: []
draft: false
output:
  blogdown::html_page
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Querría sumar un poco sobre los analísis realizados en esta pequeña página web/proyecto final sobre comercio exterior en América Latina. Además, de unas consideraciones finales sobre el uso de BlogDown y Rstudio

## Conclusión
Con estos breves analisis de los flujos de comercio exterior latinoamericanos se nota la tendencia subrayado en la introducción de que los países de América Latina tiende a exportar recursos naturales extraidos de la tierra o productos agropecarios y importar productos ya manifacturados y/o de alta tecnología. 

Unos de los principales argumentos de la trampa de los ingresos medios es que los países de América Latina necesitan desarrollar su ventaja competitiva en otros areas que la agricultura y la fabricación de alimentos, y entrar en las industrias de alta tecnología y donde se necesita mano de obra más cualificada. Para entonces poder vender productos más caros en el mercado global, fortalecer el nivel salarial de sus poblaciones.

El análisis de la evolución histórica del comercio exterior demostró que el comercio exterior de la región efectivamente aumentó bastante a través de las reformas neoliberales y en los 2000s a través del boom de commodities. Pero no parece haber cambiado mucho el régimen productivo en los países latinoamericanos, y según algunos de los autores mencionados anteriormente, se podía argumentar que por eso no se ha encontrado un camino a un desarrollo ecónomico sostentable.

Sería interesante investigar si una mejora del régimen de cualificaciones efectivamente podía empujar a las empresas latinoamericanos de invertir en sectores de mayores niveles de tecnología para producir y exportar los tipos de productos, y si eso efectivamente podía llevar a un desarrollo económico más sostenible para América Latina.

## Consideraciones finales sobre BlogDown y Rstudio
La idea de hacer una página web como trabajo final capaz fue un toque demasiado ambicioso. 

En primer lugar, porque terminé gastando todo un fin de semana largo en lograr que mi repositorio de Github se conecta correctamente a Netlify y que instala el diseño correctamente. Después tenía que hacer los analisis...

En segundo lugar, la imprevista desventaja de que cada blog post era su propio Rmarkdown documento significó que no podía reusar los data frames generado en un post y tenía que hacer las misma operaciones (como unir las diferentes bases de datos de Open Trade Statistics) en casi cada post. 

En tercer lugar, empecé a experimentar problemas con el dplyr y el error "“summarise() ungrouping output (override with .groups argument)”", lo cual resultó en que los post no se cargaban bien y no se actualizaba bien online - muy muy frustrante y muchas idas y vueltas para encontrar la solución 

En final, sí, fue un proyecto muy ambicioso y gasté una cantidad increíble de tiempo en desarrollarlo, pero también siento que aprendí un montón y me obsesioné en hacer las pequeñas partes funcionar. Encima usé R studio como un ejemplo en una entrevista de trabajo. Siento que aún me queda mucho para aprender de R studio - especialmente de la modificando y manipulación de datos - pero también siento que me he sacado el miedo de ponerme a buscar y intentar nuevas cosas en Rstudio.

Aunque queda unos pendientes que podía/quería mejorar en el proyecto, pero si no paro ahora (1) mi novio va a solicitar un "divorcio" por la cantidad de tiempo que uso frente a la computadora con Rstudio y (2) nunca voy a avanzar con la tesis :) 

¡Así hasta ahí llego! ¡Espero que hayas disfrutado revisar mi proyecto, Tucu! 
----

#### ¡Gracias! 
